services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INIT_DB}
    ports:
      - "27017:27017"
    volumes:
      - ./dataset/:/import/datasource/
      - mongodb_data:/data/db
    networks: [app-network]

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH_ENABLED: "false"
    depends_on: [mongodb]
    networks: [app-network]

  api:
    build: .
    container_name: express-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_HOST: mongodb
      HOST: 0.0.0.0
    ports:
      - "5000:5000"
    depends_on: [mongodb]
    networks: [app-network]
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
